[2024-11-24T11:49:56.411+0000] {processor.py:186} INFO - Started process (PID=2149) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:49:56.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:49:56.477+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:49:56.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:49:56.580+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:49:56.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:49:56.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:49:56.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.457 seconds
[2024-11-24T11:50:15.371+0000] {processor.py:186} INFO - Started process (PID=2154) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:15.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:15.376+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:15.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:15.412+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:15.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:50:15.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:15.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.075 seconds
[2024-11-24T11:50:20.476+0000] {processor.py:186} INFO - Started process (PID=2159) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:20.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:20.482+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:20.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:20.513+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:20.511+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 17
    da'earthquake_etl_pipeline',
      ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
[2024-11-24T11:50:20.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:20.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.085 seconds
[2024-11-24T11:50:22.611+0000] {processor.py:186} INFO - Started process (PID=2164) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:22.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:22.615+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:22.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:22.629+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:22.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 17
    dag_id'earthquake_etl_pipeline',
          ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
[2024-11-24T11:50:22.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:22.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.049 seconds
[2024-11-24T11:50:25.716+0000] {processor.py:186} INFO - Started process (PID=2175) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:25.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:25.721+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:25.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:25.808+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:25.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:50:25.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:25.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.127 seconds
[2024-11-24T11:50:39.042+0000] {processor.py:186} INFO - Started process (PID=2180) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:39.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:39.048+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:39.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:39.080+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:39.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:50:39.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:39.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.064 seconds
[2024-11-24T11:50:47.157+0000] {processor.py:186} INFO - Started process (PID=2185) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:47.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:47.163+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:47.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:47.203+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:47.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:50:47.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:47.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.081 seconds
[2024-11-24T11:50:51.320+0000] {processor.py:186} INFO - Started process (PID=2190) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:51.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:50:51.327+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:51.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:51.370+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:50:51.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:50:51.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:50:51.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.082 seconds
[2024-11-24T11:51:21.741+0000] {processor.py:186} INFO - Started process (PID=2201) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:21.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:51:21.745+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:51:21.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:21.798+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:51:21.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:51:21.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:21.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.093 seconds
[2024-11-24T11:51:52.154+0000] {processor.py:186} INFO - Started process (PID=2212) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:52.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:51:52.158+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:51:52.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:52.182+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:51:52.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:51:52.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:51:52.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.056 seconds
[2024-11-24T11:52:22.566+0000] {processor.py:186} INFO - Started process (PID=2223) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:22.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:22.572+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:22.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:22.618+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:22.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:22.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:22.657+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.101 seconds
[2024-11-24T11:52:42.977+0000] {processor.py:186} INFO - Started process (PID=2234) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:42.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:42.983+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:42.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:43.073+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:43.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:43.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:43.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.147 seconds
[2024-11-24T11:52:47.047+0000] {processor.py:186} INFO - Started process (PID=2239) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:47.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:47.051+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:47.051+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:47.125+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:47.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:47.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:47.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.110 seconds
[2024-11-24T11:52:50.079+0000] {processor.py:186} INFO - Started process (PID=2244) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:50.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:50.084+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:50.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:50.143+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:50.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:50.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:50.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.103 seconds
[2024-11-24T11:52:52.130+0000] {processor.py:186} INFO - Started process (PID=2249) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:52.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:52.134+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:52.134+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:52.216+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:52.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:52.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:52.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.121 seconds
[2024-11-24T11:52:53.289+0000] {processor.py:186} INFO - Started process (PID=2260) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:53.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:53.297+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:53.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:53.364+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:53.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:53.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:53.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.117 seconds
[2024-11-24T11:52:56.348+0000] {processor.py:186} INFO - Started process (PID=2265) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:56.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:56.352+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:56.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:56.377+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:56.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:56.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:56.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.054 seconds
[2024-11-24T11:52:57.400+0000] {processor.py:186} INFO - Started process (PID=2270) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:57.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:52:57.406+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:57.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:57.501+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:52:57.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:52:57.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:52:57.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.145 seconds
[2024-11-24T11:53:01.528+0000] {processor.py:186} INFO - Started process (PID=2275) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:01.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:01.532+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:01.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:01.613+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:01.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:01.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:01.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.117 seconds
[2024-11-24T11:53:02.657+0000] {processor.py:186} INFO - Started process (PID=2280) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:02.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:02.661+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:02.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:02.723+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:02.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:02.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:02.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.095 seconds
[2024-11-24T11:53:24.956+0000] {processor.py:186} INFO - Started process (PID=2291) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:24.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:24.961+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:24.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:24.985+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:24.983+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 26
    if now==dag.:
                ^
SyntaxError: invalid syntax
[2024-11-24T11:53:24.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:25.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.063 seconds
[2024-11-24T11:53:28.075+0000] {processor.py:186} INFO - Started process (PID=2296) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:28.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:28.079+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:28.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:28.158+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:28.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:28.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:28.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.121 seconds
[2024-11-24T11:53:30.131+0000] {processor.py:186} INFO - Started process (PID=2301) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:30.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:30.136+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:30.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:30.175+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:30.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:30.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:30.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.074 seconds
[2024-11-24T11:53:34.193+0000] {processor.py:186} INFO - Started process (PID=2306) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:34.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:34.196+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:34.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:34.254+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:34.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:34.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:34.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.094 seconds
[2024-11-24T11:53:40.385+0000] {processor.py:186} INFO - Started process (PID=2311) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:40.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:40.391+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:40.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:40.477+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:40.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:40.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:40.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.131 seconds
[2024-11-24T11:53:42.458+0000] {processor.py:186} INFO - Started process (PID=2316) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:42.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:42.463+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:42.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:42.555+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:42.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:42.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:42.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.133 seconds
[2024-11-24T11:53:44.639+0000] {processor.py:186} INFO - Started process (PID=2321) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:44.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:44.643+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:44.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:44.725+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:44.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:44.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:44.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.115 seconds
[2024-11-24T11:53:45.676+0000] {processor.py:186} INFO - Started process (PID=2326) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:45.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:45.680+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:45.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:45.724+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:45.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:45.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:45.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.079 seconds
[2024-11-24T11:53:51.764+0000] {processor.py:186} INFO - Started process (PID=2331) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:51.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:51.768+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:51.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:51.833+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:51.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:51.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:51.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.098 seconds
[2024-11-24T11:53:52.948+0000] {processor.py:186} INFO - Started process (PID=2336) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:52.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:52.953+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:52.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:53.002+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:52.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:53.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:53.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.091 seconds
[2024-11-24T11:53:56.014+0000] {processor.py:186} INFO - Started process (PID=2347) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:56.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:56.018+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:56.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:56.100+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:56.091+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:56.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:56.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.122 seconds
[2024-11-24T11:53:57.146+0000] {processor.py:186} INFO - Started process (PID=2352) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:57.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:57.151+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:57.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:57.198+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:57.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:57.200+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:57.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.087 seconds
[2024-11-24T11:53:59.259+0000] {processor.py:186} INFO - Started process (PID=2357) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:59.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:53:59.265+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:59.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:59.335+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:53:59.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:53:59.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:53:59.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.112 seconds
[2024-11-24T11:54:03.374+0000] {processor.py:186} INFO - Started process (PID=2362) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:03.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:03.380+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:03.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:03.465+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:03.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:03.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:03.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.146 seconds
[2024-11-24T11:54:07.508+0000] {processor.py:186} INFO - Started process (PID=2367) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:07.509+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:07.512+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:07.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:07.547+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:07.543+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:07.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:07.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.067 seconds
[2024-11-24T11:54:10.593+0000] {processor.py:186} INFO - Started process (PID=2372) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:10.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:10.597+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:10.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:10.672+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:10.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:10.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:10.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.109 seconds
[2024-11-24T11:54:11.725+0000] {processor.py:186} INFO - Started process (PID=2377) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:11.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:11.729+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:11.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:11.781+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:11.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:11.783+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:11.806+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.088 seconds
[2024-11-24T11:54:15.833+0000] {processor.py:186} INFO - Started process (PID=2382) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:15.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:15.836+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:15.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:15.917+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:15.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:15.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:15.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.115 seconds
[2024-11-24T11:54:17.943+0000] {processor.py:186} INFO - Started process (PID=2387) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:17.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:17.947+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:17.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:18.012+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:18.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:18.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:18.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.105 seconds
[2024-11-24T11:54:19.031+0000] {processor.py:186} INFO - Started process (PID=2392) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:19.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:19.035+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:19.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:19.083+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:19.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:19.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:19.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.083 seconds
[2024-11-24T11:54:24.156+0000] {processor.py:186} INFO - Started process (PID=2403) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:24.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:24.161+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:24.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:24.189+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:24.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:24.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:24.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.069 seconds
[2024-11-24T11:54:30.269+0000] {processor.py:186} INFO - Started process (PID=2408) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:30.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:30.273+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:30.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:30.346+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:30.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:30.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:30.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.109 seconds
[2024-11-24T11:54:32.377+0000] {processor.py:186} INFO - Started process (PID=2413) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:32.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:32.381+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:32.381+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:32.461+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:32.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:32.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:32.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.117 seconds
[2024-11-24T11:54:35.505+0000] {processor.py:186} INFO - Started process (PID=2418) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:35.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:54:35.510+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:35.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:35.593+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:54:35.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:54:35.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:54:35.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.125 seconds
[2024-11-24T11:55:06.027+0000] {processor.py:186} INFO - Started process (PID=2429) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:06.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:06.032+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:06.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:06.067+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:06.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:06.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:06.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.079 seconds
[2024-11-24T11:55:32.419+0000] {processor.py:186} INFO - Started process (PID=2440) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:32.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:32.425+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:32.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:32.514+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:32.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:32.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:32.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.140 seconds
[2024-11-24T11:55:35.653+0000] {processor.py:186} INFO - Started process (PID=2445) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:35.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:35.659+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:35.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:35.704+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:35.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:35.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:35.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.088 seconds
[2024-11-24T11:55:40.755+0000] {processor.py:186} INFO - Started process (PID=2450) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:40.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:40.760+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:40.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:40.845+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:40.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:40.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:40.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.131 seconds
[2024-11-24T11:55:44.907+0000] {processor.py:186} INFO - Started process (PID=2455) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:44.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:44.912+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:44.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:44.993+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:44.979+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:44.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:45.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.129 seconds
[2024-11-24T11:55:50.078+0000] {processor.py:186} INFO - Started process (PID=2460) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:50.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:55:50.083+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:50.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:50.127+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:55:50.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:55:50.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:55:50.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.072 seconds
[2024-11-24T11:56:09.330+0000] {processor.py:186} INFO - Started process (PID=2471) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:09.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:09.337+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:09.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:09.371+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:09.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:09.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:09.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.071 seconds
[2024-11-24T11:56:13.418+0000] {processor.py:186} INFO - Started process (PID=2476) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:13.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:13.423+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:13.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:13.473+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:13.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:13.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:13.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.098 seconds
[2024-11-24T11:56:17.549+0000] {processor.py:186} INFO - Started process (PID=2481) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:17.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:17.555+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:17.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:17.636+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:17.624+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:17.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:17.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.129 seconds
[2024-11-24T11:56:20.636+0000] {processor.py:186} INFO - Started process (PID=2486) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:20.638+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:20.642+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:20.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:20.699+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:20.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:20.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:20.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.092 seconds
[2024-11-24T11:56:49.079+0000] {processor.py:186} INFO - Started process (PID=2497) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:49.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:49.085+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:49.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:49.124+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:49.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:49.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:49.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.082 seconds
[2024-11-24T11:56:50.133+0000] {processor.py:186} INFO - Started process (PID=2502) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:50.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:50.139+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:50.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:50.200+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:50.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:50.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:50.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.106 seconds
[2024-11-24T11:56:53.279+0000] {processor.py:186} INFO - Started process (PID=2507) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:53.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:53.283+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:53.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:53.390+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:53.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:53.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:53.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.140 seconds
[2024-11-24T11:56:57.372+0000] {processor.py:186} INFO - Started process (PID=2518) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:57.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:56:57.376+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:57.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:57.453+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:56:57.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:56:57.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:56:57.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.111 seconds
[2024-11-24T11:57:02.584+0000] {processor.py:186} INFO - Started process (PID=2523) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:02.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:02.588+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:02.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:02.682+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:02.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:02.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:02.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.130 seconds
[2024-11-24T11:57:05.634+0000] {processor.py:186} INFO - Started process (PID=2528) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:05.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:05.638+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:05.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:05.692+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:05.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:05.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:05.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.095 seconds
[2024-11-24T11:57:08.817+0000] {processor.py:186} INFO - Started process (PID=2533) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:08.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:08.822+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:08.821+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:08.852+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:08.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:08.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:08.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.063 seconds
[2024-11-24T11:57:12.975+0000] {processor.py:186} INFO - Started process (PID=2538) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:12.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:12.980+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:12.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:13.061+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:13.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:13.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:13.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.136 seconds
[2024-11-24T11:57:27.102+0000] {processor.py:186} INFO - Started process (PID=2549) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:27.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:27.107+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:27.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:27.129+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:27.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:27.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:27.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.051 seconds
[2024-11-24T11:57:32.210+0000] {processor.py:186} INFO - Started process (PID=2554) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:32.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:32.215+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:32.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:32.274+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:32.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:32.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:32.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.094 seconds
[2024-11-24T11:57:36.305+0000] {processor.py:186} INFO - Started process (PID=2559) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:36.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:57:36.310+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:36.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:36.376+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:57:36.369+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:57:36.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:57:36.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.105 seconds
[2024-11-24T11:58:06.766+0000] {processor.py:186} INFO - Started process (PID=2570) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:06.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:06.770+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:06.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:06.812+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:06.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:06.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:06.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.081 seconds
[2024-11-24T11:58:37.138+0000] {processor.py:186} INFO - Started process (PID=2581) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:37.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:37.142+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:37.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:37.194+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:37.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:37.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:37.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.089 seconds
[2024-11-24T11:58:40.200+0000] {processor.py:186} INFO - Started process (PID=2586) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:40.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:40.206+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:40.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:40.286+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:40.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:40.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:40.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.126 seconds
[2024-11-24T11:58:42.360+0000] {processor.py:186} INFO - Started process (PID=2591) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:42.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:42.366+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:42.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:42.446+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:42.435+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:42.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:42.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.124 seconds
[2024-11-24T11:58:46.461+0000] {processor.py:186} INFO - Started process (PID=2596) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:46.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:46.465+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:46.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:46.545+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:46.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:46.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:46.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.122 seconds
[2024-11-24T11:58:51.696+0000] {processor.py:186} INFO - Started process (PID=2601) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:51.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:51.702+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:51.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:51.760+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:51.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:51.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:51.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.107 seconds
[2024-11-24T11:58:53.715+0000] {processor.py:186} INFO - Started process (PID=2606) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:53.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:53.719+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:53.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:53.772+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:53.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:53.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:53.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.094 seconds
[2024-11-24T11:58:56.777+0000] {processor.py:186} INFO - Started process (PID=2617) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:56.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:56.780+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:56.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:56.839+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:56.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:56.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:56.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.085 seconds
[2024-11-24T11:58:58.915+0000] {processor.py:186} INFO - Started process (PID=2622) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:58.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:58:58.919+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:58.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:58.955+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:58:58.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:58:58.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:58:58.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.074 seconds
[2024-11-24T11:59:01.985+0000] {processor.py:186} INFO - Started process (PID=2627) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:01.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:01.989+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:01.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:02.050+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:02.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:02.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:02.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.094 seconds
[2024-11-24T11:59:32.413+0000] {processor.py:186} INFO - Started process (PID=2638) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:32.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:32.420+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:32.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:32.470+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:32.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:32.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:32.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.092 seconds
[2024-11-24T11:59:39.523+0000] {processor.py:186} INFO - Started process (PID=2643) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:39.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:39.531+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:39.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:39.581+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:39.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:39.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:39.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.094 seconds
[2024-11-24T11:59:42.721+0000] {processor.py:186} INFO - Started process (PID=2648) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:42.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:42.725+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:42.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:42.821+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:42.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:42.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:42.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.129 seconds
[2024-11-24T11:59:47.962+0000] {processor.py:186} INFO - Started process (PID=2653) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:47.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:47.966+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:47.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:48.040+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:48.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:48.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:48.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.111 seconds
[2024-11-24T11:59:48.976+0000] {processor.py:186} INFO - Started process (PID=2658) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:48.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:48.980+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:48.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:49.041+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:49.031+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:49.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:49.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.096 seconds
[2024-11-24T11:59:51.004+0000] {processor.py:186} INFO - Started process (PID=2663) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:51.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:51.009+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:51.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:51.050+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:51.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:51.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:51.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.074 seconds
[2024-11-24T11:59:55.092+0000] {processor.py:186} INFO - Started process (PID=2674) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:55.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T11:59:55.097+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:55.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:55.162+0000] {logging_mixin.py:190} INFO - [2024-11-24T11:59:55.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T11:59:55.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T11:59:55.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.107 seconds
[2024-11-24T12:00:12.458+0000] {processor.py:186} INFO - Started process (PID=2679) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:12.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:00:12.462+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:00:12.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:12.536+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:00:12.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:00:12.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:12.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.105 seconds
[2024-11-24T12:00:35.755+0000] {processor.py:186} INFO - Started process (PID=2691) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:35.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:00:35.759+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:00:35.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:35.837+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:00:35.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:00:35.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:00:35.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.112 seconds
[2024-11-24T12:01:04.196+0000] {processor.py:186} INFO - Started process (PID=2702) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:04.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:01:04.202+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:04.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:04.251+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:04.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:01:04.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:04.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.082 seconds
[2024-11-24T12:01:07.360+0000] {processor.py:186} INFO - Started process (PID=2707) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:07.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:01:07.364+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:07.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:07.455+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:07.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:01:07.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:07.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.131 seconds
[2024-11-24T12:01:10.399+0000] {processor.py:186} INFO - Started process (PID=2712) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:10.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:01:10.403+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:10.403+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:10.427+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:10.424+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:01:10.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:10.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.057 seconds
[2024-11-24T12:01:40.760+0000] {processor.py:186} INFO - Started process (PID=2723) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:40.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:01:40.765+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:40.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:40.816+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:01:40.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:01:40.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:01:40.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.089 seconds
[2024-11-24T12:02:11.160+0000] {processor.py:186} INFO - Started process (PID=2734) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:11.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:02:11.164+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:02:11.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:11.217+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:02:11.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:02:11.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:11.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.086 seconds
[2024-11-24T12:02:41.594+0000] {processor.py:186} INFO - Started process (PID=2745) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:41.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:02:41.598+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:02:41.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:41.650+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:02:41.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:02:41.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:02:41.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.088 seconds
[2024-11-24T12:03:12.079+0000] {processor.py:186} INFO - Started process (PID=2756) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:12.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:03:12.084+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:03:12.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:12.137+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:03:12.125+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:03:12.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:12.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.095 seconds
[2024-11-24T12:03:42.591+0000] {processor.py:186} INFO - Started process (PID=2767) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:42.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:03:42.603+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:03:42.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:42.625+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:03:42.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:03:42.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:03:42.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.158 seconds
[2024-11-24T12:04:12.908+0000] {processor.py:186} INFO - Started process (PID=2778) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:12.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:04:12.913+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:04:12.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:12.939+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:04:12.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:04:12.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:12.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.066 seconds
[2024-11-24T12:04:43.253+0000] {processor.py:186} INFO - Started process (PID=2789) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:43.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:04:43.261+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:04:43.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:43.312+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:04:43.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:04:43.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:04:43.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.101 seconds
[2024-11-24T12:05:13.769+0000] {processor.py:186} INFO - Started process (PID=2799) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:13.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:05:13.774+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:05:13.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:13.814+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:05:13.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:05:13.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:13.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.073 seconds
[2024-11-24T12:05:44.195+0000] {processor.py:186} INFO - Started process (PID=2810) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:44.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:05:44.200+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:05:44.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:44.249+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:05:44.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:05:44.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:05:44.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.093 seconds
[2024-11-24T12:06:14.531+0000] {processor.py:186} INFO - Started process (PID=2821) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:14.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:06:14.536+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:06:14.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:14.559+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:06:14.553+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:06:14.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:14.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.080 seconds
[2024-11-24T12:06:44.909+0000] {processor.py:186} INFO - Started process (PID=2832) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:44.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:06:44.914+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:06:44.914+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:45.139+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:06:45.083+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:06:45.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:06:45.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.333 seconds
[2024-11-24T12:07:15.297+0000] {processor.py:186} INFO - Started process (PID=2843) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:15.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:07:15.303+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:07:15.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:15.334+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:07:15.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:07:15.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:15.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.074 seconds
[2024-11-24T12:07:45.655+0000] {processor.py:186} INFO - Started process (PID=2854) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:45.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:07:45.660+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:07:45.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:45.703+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:07:45.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:07:45.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:07:45.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.093 seconds
[2024-11-24T12:08:16.057+0000] {processor.py:186} INFO - Started process (PID=2865) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:16.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:08:16.063+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:08:16.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:16.118+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:08:16.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:08:16.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:16.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.097 seconds
[2024-11-24T12:08:46.503+0000] {processor.py:186} INFO - Started process (PID=2875) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:46.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:08:46.508+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:08:46.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:46.564+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:08:46.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:08:46.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:08:46.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.092 seconds
[2024-11-24T12:09:16.960+0000] {processor.py:186} INFO - Started process (PID=2886) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:16.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:09:16.992+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:09:16.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:17.096+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:09:17.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:09:17.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:17.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.215 seconds
[2024-11-24T12:09:47.299+0000] {processor.py:186} INFO - Started process (PID=2897) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:47.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:09:47.303+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:09:47.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:47.334+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:09:47.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:09:47.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:09:47.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.069 seconds
[2024-11-24T12:10:02.491+0000] {processor.py:186} INFO - Started process (PID=2908) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:02.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:10:02.496+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:02.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:02.532+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:02.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.fetch_data import fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:10:02.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:02.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.081 seconds
[2024-11-24T12:10:28.918+0000] {processor.py:186} INFO - Started process (PID=2919) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:28.920+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:10:28.925+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:28.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:28.998+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:28.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:10:29.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:29.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.114 seconds
[2024-11-24T12:10:48.232+0000] {processor.py:186} INFO - Started process (PID=2924) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:48.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:10:48.239+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:48.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:48.274+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:10:48.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:10:48.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:10:48.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.081 seconds
[2024-11-24T12:11:01.394+0000] {processor.py:186} INFO - Started process (PID=2935) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:01.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:01.399+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:01.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:01.432+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:01.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:01.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:01.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.066 seconds
[2024-11-24T12:11:05.525+0000] {processor.py:186} INFO - Started process (PID=2940) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:05.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:05.532+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:05.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:05.607+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:05.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:05.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:05.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.122 seconds
[2024-11-24T12:11:09.603+0000] {processor.py:186} INFO - Started process (PID=2945) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:09.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:09.609+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:09.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:09.689+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:09.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:09.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:09.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.127 seconds
[2024-11-24T12:11:27.924+0000] {processor.py:186} INFO - Started process (PID=2956) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:27.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:27.928+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:27.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:27.957+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:27.953+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:27.958+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:27.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.061 seconds
[2024-11-24T12:11:31.987+0000] {processor.py:186} INFO - Started process (PID=2961) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:31.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:31.993+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:31.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:32.031+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:32.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:32.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:32.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.084 seconds
[2024-11-24T12:11:33.091+0000] {processor.py:186} INFO - Started process (PID=2966) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:33.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:11:33.095+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:33.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:33.139+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:11:33.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:11:33.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:11:33.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.083 seconds
[2024-11-24T12:12:03.457+0000] {processor.py:186} INFO - Started process (PID=2977) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:03.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:12:03.464+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:03.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:03.501+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:03.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:12:03.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:03.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.084 seconds
[2024-11-24T12:12:24.793+0000] {processor.py:186} INFO - Started process (PID=2982) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:24.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:12:24.799+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:24.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:24.853+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:24.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:12:24.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:24.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.098 seconds
[2024-11-24T12:12:55.221+0000] {processor.py:186} INFO - Started process (PID=2993) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:55.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:12:55.225+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:55.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:55.282+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:12:55.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:12:55.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:12:55.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.092 seconds
[2024-11-24T12:13:16.495+0000] {processor.py:186} INFO - Started process (PID=3003) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:16.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:16.501+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:16.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:16.578+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:16.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:13:16.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:16.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.120 seconds
[2024-11-24T12:13:20.632+0000] {processor.py:186} INFO - Started process (PID=3008) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:20.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:20.634+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:20.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:20.655+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:20.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:13:20.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:20.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.049 seconds
[2024-11-24T12:13:23.770+0000] {processor.py:186} INFO - Started process (PID=3013) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:23.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:23.774+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:23.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:23.839+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:23.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 50
    return {'encodedData': encodedData, 'scalar': scaler, ''}
                                                           ^
SyntaxError: ':' expected after dictionary key
[2024-11-24T12:13:23.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:23.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.103 seconds
[2024-11-24T12:13:27.845+0000] {processor.py:186} INFO - Started process (PID=3024) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:27.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:27.849+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:27.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:27.900+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:27.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 50
    return {'encodedData': encodedData, 'scalar': scaler, 'encoder'}
                                                                  ^
SyntaxError: ':' expected after dictionary key
[2024-11-24T12:13:27.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:27.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.090 seconds
[2024-11-24T12:13:31.106+0000] {processor.py:186} INFO - Started process (PID=3029) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:31.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:31.112+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:31.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:31.146+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:31.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:13:31.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:31.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.080 seconds
[2024-11-24T12:13:32.191+0000] {processor.py:186} INFO - Started process (PID=3034) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:32.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:13:32.197+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:32.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:32.264+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:13:32.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:13:32.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:13:32.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.111 seconds
[2024-11-24T12:14:02.606+0000] {processor.py:186} INFO - Started process (PID=3045) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:02.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:02.611+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:02.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:02.641+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:02.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:02.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:02.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.084 seconds
[2024-11-24T12:14:09.741+0000] {processor.py:186} INFO - Started process (PID=3050) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:09.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:09.747+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:09.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:09.786+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:09.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:09.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:09.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.069 seconds
[2024-11-24T12:14:13.851+0000] {processor.py:186} INFO - Started process (PID=3055) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:13.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:13.857+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:13.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:13.893+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:13.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:13.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:13.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.077 seconds
[2024-11-24T12:14:18.010+0000] {processor.py:186} INFO - Started process (PID=3060) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:18.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:18.014+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:18.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:18.041+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:18.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:18.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:18.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.054 seconds
[2024-11-24T12:14:19.099+0000] {processor.py:186} INFO - Started process (PID=3065) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:19.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:19.106+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:19.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:19.173+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:19.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:19.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:19.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.121 seconds
[2024-11-24T12:14:49.513+0000] {processor.py:186} INFO - Started process (PID=3076) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:49.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:14:49.519+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:49.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:49.572+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:14:49.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:14:49.575+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:14:49.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.089 seconds
[2024-11-24T12:15:20.062+0000] {processor.py:186} INFO - Started process (PID=3087) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:20.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:15:20.066+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:15:20.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:20.099+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:15:20.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:15:20.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:20.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.074 seconds
[2024-11-24T12:15:50.457+0000] {processor.py:186} INFO - Started process (PID=3098) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:50.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:15:50.461+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:15:50.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:50.504+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:15:50.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:15:50.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:15:50.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.104 seconds
[2024-11-24T12:16:20.825+0000] {processor.py:186} INFO - Started process (PID=3109) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:20.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:16:20.834+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:16:20.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:20.877+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:16:20.867+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:16:20.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:20.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.092 seconds
[2024-11-24T12:16:51.215+0000] {processor.py:186} INFO - Started process (PID=3120) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:51.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:16:51.220+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:16:51.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:51.278+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:16:51.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:16:51.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:16:51.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.098 seconds
[2024-11-24T12:17:21.590+0000] {processor.py:186} INFO - Started process (PID=3131) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:21.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:17:21.596+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:17:21.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:21.634+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:17:21.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:17:21.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:21.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.077 seconds
[2024-11-24T12:17:51.053+0000] {processor.py:186} INFO - Started process (PID=3142) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:51.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:17:51.061+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:17:51.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:51.112+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:17:51.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:17:51.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:17:51.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.105 seconds
[2024-11-24T12:18:03.226+0000] {processor.py:186} INFO - Started process (PID=3153) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:03.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:18:03.232+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:03.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:03.289+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:03.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:18:03.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:03.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.101 seconds
[2024-11-24T12:18:11.444+0000] {processor.py:186} INFO - Started process (PID=3158) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:11.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:18:11.449+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:11.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:11.538+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:11.526+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:18:11.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:11.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.131 seconds
[2024-11-24T12:18:14.511+0000] {processor.py:186} INFO - Started process (PID=3163) to work on /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:14.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etlDag.py for tasks to queue
[2024-11-24T12:18:14.516+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:14.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:14.575+0000] {logging_mixin.py:190} INFO - [2024-11-24T12:18:14.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etlDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etlDag.py", line 4, in <module>
    from src.dataRetrival import setTime,fetchFromApi
ModuleNotFoundError: No module named 'src'
[2024-11-24T12:18:14.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etlDag.py
[2024-11-24T12:18:14.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etlDag.py took 0.102 seconds
