[2024-11-25T09:13:50.577+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T09:13:50.619+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_PipelineV31.pushDataToAzure scheduled__2024-11-25T08:00:00+00:00 [queued]>
[2024-11-25T09:13:50.640+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_PipelineV31.pushDataToAzure scheduled__2024-11-25T08:00:00+00:00 [queued]>
[2024-11-25T09:13:50.642+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2024-11-25T09:13:50.670+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): pushDataToAzure> on 2024-11-25 08:00:00+00:00
[2024-11-25T09:13:50.729+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_PipelineV31', 'pushDataToAzure', 'scheduled__2024-11-25T08:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etlDag.py', '--cfg-path', '/tmp/tmpp2tncp5d']
[2024-11-25T09:13:50.730+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-25T09:13:50.734+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask pushDataToAzure
[2024-11-25T09:13:50.734+0000] {standard_task_runner.py:72} INFO - Started process 5244 to run task
[2024-11-25T09:13:50.842+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_PipelineV31.pushDataToAzure scheduled__2024-11-25T08:00:00+00:00 [running]> on host 7939e06e2b4b
[2024-11-25T09:13:51.065+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Oshith Roshantha' AIRFLOW_CTX_DAG_ID='etl_PipelineV31' AIRFLOW_CTX_TASK_ID='pushDataToAzure' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T08:00:00+00:00'
[2024-11-25T09:13:51.067+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T09:13:51.386+0000] {environment.py:115} INFO - No environment configuration found.
[2024-11-25T09:13:51.392+0000] {managed_identity.py:117} INFO - ManagedIdentityCredential will use IMDS
[2024-11-25T09:13:51.403+0000] {_universal.py:509} INFO - Request URL: 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.19.0 Python/3.12.7 (Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36)'
No body was attached to the request
[2024-11-25T09:13:51.926+0000] {chained.py:218} WARNING - DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
	AzureCliCredential: Azure CLI not found on path
	AzurePowerShellCredential: PowerShell is not installed
	AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
